CC = gcc CFLAGS = -O1 - g -
                  Wall

                      MFILES : = main.c tree.c

                                     main
    : $(MFILES) $(CC) $ ^ -o $ @$(CFLAGS)


                                         clean
    : rm - f main